# Generated by Django 3.2.1 on 2021-06-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20210602_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Cash on delivery', 'Cash on delivery'), ('Paypal', 'Paypal')], max_length=50),
        ),
    ]
