# Generated by Django 3.2.1 on 2021-06-03 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal'), ('Cash on delivery', 'Cash on delivery')], max_length=50, null=True),
        ),
    ]
