# Generated by Django 3.2.1 on 2021-06-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20210603_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='myshop.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe'), ('C', 'Cash on delivery')], max_length=1, null=True),
        ),
    ]
