# Generated by Django 3.2.1 on 2021-06-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20210609_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='Laptop', on_delete=django.db.models.deletion.CASCADE, to='myshop.product'),
        ),
    ]
