# Generated by Django 3.2.1 on 2021-06-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='myshop.product'),
        ),
    ]
