# Generated by Django 3.2.1 on 2021-06-09 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
