# Generated by Django 3.2.1 on 2021-06-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
