# Generated by Django 3.2.1 on 2021-07-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0015_auto_20210628_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prod_size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
