# Generated by Django 3.2.1 on 2021-07-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_cart_prod_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
